### ISSUE TITLE
Feature-request

### ISSUE THREAD

**Issue by os1r1s110** [nabinked/NToastNotify#1]
Hi there, nice little library you've got there!

It would be nice if it would be possible to change the default options for the toastr notification (by calling the service), so we don't have to do it every time we call the "AddToastMessage".

Thanks for your work!

**Comment by nabinked** [comment]
@os1r1s110 Definitely. I have not been able to put some time on it. I understand what you mean. We can add default settings at the time of service registration at the start up of the application and the library can use it through out the application. I will try to implement this as soon as possible. Thanks

**Comment by nabinked** [comment]
done in commit [008ecf1](https://github.com/nabinked/NToastNotify/commit/008ecf198a97996c2fa3896a5863bc2cbb9bfad4)
Please let me know if it is not working

**Comment by os1r1s110** [comment]
Nice, I'll take a look and tell you if I see something wrong! Thanks for this super quick reaction and (IMO) really nice feature added.

**Comment by nabinked** [comment]
Not a problem at all. Cheers.
