### ISSUE TITLE
ViewComponent not found

### ISSUE THREAD

**Issue by os1r1s110** [nabinked/NToastNotify#101]
I'm in the process of migrating to Asp.Net Core 3.0, and I get the following error:
`A view component named 'NToastNotify' could not be found. A view component must be a public non-abstract class, not contain any generic parameters, and either be decorated with 'ViewComponentAttribute' or have a class name ending with the 'ViewComponent' suffix. A view component must not be decorated with 'NonViewComponentAttribute'.`

To be noted that I did update to latest version (6.0.1) before trying.

I tried finding the root cause, but I found that you effectively did update the project file to include 
```
<PropertyGroup>
  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
</PropertyGroup>
```
So I'm wondering what else could cause the ViewComponent to not be found.... Would you have an idea?

**Comment by os1r1s110** [comment]
When I go to install the Nuget package, here's what VS tells me:

> Updates:
> 
> Microsoft.AspNetCore.Antiforgery.2.0.1 -> Microsoft.AspNetCore.Antiforgery.2.2.0
> Microsoft.AspNetCore.Authentication.Abstractions.2.0.1 -> Microsoft.AspNetCore.Authentication.Abstractions.2.2.0
> Microsoft.AspNetCore.Authentication.Core.2.0.1 -> Microsoft.AspNetCore.Authentication.Core.2.2.0
> Microsoft.AspNetCore.Authorization.2.0.1 -> Microsoft.AspNetCore.Authorization.2.2.0
> Microsoft.AspNetCore.Authorization.Policy.2.0.1 -> Microsoft.AspNetCore.Authorization.Policy.2.2.0
> Microsoft.AspNetCore.DataProtection.2.0.1 -> Microsoft.AspNetCore.DataProtection.2.2.0
> Microsoft.AspNetCore.DataProtection.Abstractions.2.0.1 -> Microsoft.AspNetCore.DataProtection.Abstractions.2.2.0
> Microsoft.AspNetCore.Diagnostics.Abstractions.2.1.0 -> Microsoft.AspNetCore.Diagnostics.Abstractions.2.2.0
> Microsoft.AspNetCore.Http.2.1.0 -> Microsoft.AspNetCore.Http.2.2.0
> Microsoft.AspNetCore.Mvc.Abstractions.2.0.2 -> Microsoft.AspNetCore.Mvc.Abstractions.2.2.0
> Microsoft.AspNetCore.Mvc.Core.2.0.2 -> Microsoft.AspNetCore.Mvc.Core.2.2.0
> Microsoft.AspNetCore.Mvc.DataAnnotations.2.0.2 -> Microsoft.AspNetCore.Mvc.DataAnnotations.2.2.0
> Microsoft.AspNetCore.Mvc.Formatters.Json.2.0.2 -> Microsoft.AspNetCore.Mvc.Formatters.Json.2.2.0
> Microsoft.AspNetCore.Mvc.ViewFeatures.2.0.2 -> Microsoft.AspNetCore.Mvc.ViewFeatures.2.2.0
> Microsoft.AspNetCore.ResponseCaching.Abstractions.2.0.1 -> Microsoft.AspNetCore.ResponseCaching.Abstractions.2.2.0
> Microsoft.AspNetCore.Routing.2.0.1 -> Microsoft.AspNetCore.Routing.2.2.0
> Microsoft.AspNetCore.Routing.Abstractions.2.0.1 -> Microsoft.AspNetCore.Routing.Abstractions.2.2.0
> Microsoft.AspNetCore.WebUtilities.2.1.0 -> Microsoft.AspNetCore.WebUtilities.2.2.0
> Microsoft.Extensions.Localization.2.0.1 -> Microsoft.Extensions.Localization.2.2.0
> Microsoft.Extensions.Localization.Abstractions.2.0.1 -> Microsoft.Extensions.Localization.Abstractions.2.2.0
> Microsoft.Extensions.ObjectPool.2.1.0 -> Microsoft.Extensions.ObjectPool.2.2.0
> Microsoft.Extensions.WebEncoders.2.0.0 -> Microsoft.Extensions.WebEncoders.2.2.0
> System.Security.Cryptography.Xml.4.4.0 -> System.Security.Cryptography.Xml.4.5.0
> 
> Installing:
> 
> Microsoft.AspNetCore.StaticFiles.2.2.0
> NToastNotify.6.0.1
> 
Why would it update so much dependencies to 2.2.x?

**Comment by os1r1s110** [comment]
Doesn't seem to be related.. damnit I really can't find what's happening, it works perfectly in a brand new project...

**Comment by nabinked** [comment]
Its a good idea to follow this strictly https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

**Comment by os1r1s110** [comment]
Yeah that's what I did... I will try to remove most of the middleware in the pipeline until I find the culprit (hoping that will work). It must has something to do with some of my custom view location expanders or similar...

**Comment by os1r1s110** [comment]
Wow.... 
I finally found a fix (maybe not the only solution as I still don't understand the root problem here, but it now works after adding the following in my csproj. 
'''
    <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>ThatsASecret</UserSecretsId>
    <RootNamespace>ProjectName</RootNamespace>
  </PropertyGroup>
'''

This is not documented at all on the migration page so it was pretty hard to find as the error did not mean anything (just said it couldn't find the ViewComponent)

**Comment by nabinked** [comment]
So wierd. Will keep that in mind.

**Comment by os1r1s110** [comment]
To be clear, it still doesn't work. When I did overwrite the View Component, it started working, but that's not a solution in the long term.

Even weirder now, if I clean and rebuild the project, it works about 50% of the time... I'm completely lost lol

**Comment by os1r1s110** [comment]
It seems like sometimes, the ViewComponent is registered correctly in the `ViewComponentDescriptorProvider`, but sometimes it's not... I wonder if there's a kind of racing condition or similar that would sometimes prevent it being registered correctly.... 

Trying to figure out what could cause this kind of problem but it's not an easy task

**Comment by os1r1s110** [comment]
As I'm going down the rabbit hole, I find myself realizing that it's the `ViewComponentFeatureProvider ` that fails to find the `ViewComponent` and based on this [SO answer](https://stackoverflow.com/a/50065136), the consuming apps should add the `.AddMvc.AddApplicationPart("NToastNotify")`, but in your examples, it's not required and it still works, how so? 

How does the `ViewComponentFeatureProvider `actually find the VC?

**Comment by os1r1s110** [comment]
Wow I seem to only get deeper and deeper. Now I even tried setting up the `Application Parts Discovery` by following [this ](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.0), but as I understand it after all the reading, you have a `Razor Class Library` and it shouldn't be required to manually add the application parts like I tried (which didn't even work!). 

The things that really bothers me is if I'm listing the available features (like explained at the end of the link I provided above), I can clearly see the `NToastNotifyViewComponent` in the list of available ViewComponents, yet when I try to render, it fails spitting the error msg as above...

**Comment by os1r1s110** [comment]
Seems like the problem really lies within some of my configuration in Startup as I can't even render reliably a Razor Class Library View Component that I create and directly link to the project... I guess i'll close the issue here as it seems more related to the upgrade from 2.2 to 3.0 in my case. 

Sorry for bothering :)

**Comment by nabinked** [comment]
All good mate. Hope you can resolve your issue soon. 👍

**Comment by os1r1s110** [comment]
Just for completeness, I finally found the bug. It was related to Resharper Ultimate. After updating it to latest version and cleaning up all the Nuget caches everywhere (also repaired .net core 3 SDK, but that didn't change a thing), it started working again. 

Now, RCL are a really nice way to share UI components when they work correctly hehe!

**Comment by davidbuckleyni** [comment]
A clean and rebuild as suggested above worked for me to seems to be an issue when merging in from another branch.
