### ISSUE TITLE
.NET Core 2.2 issue

### ISSUE THREAD

**Issue by Hameds** [nabinked/NToastNotify#104]
Hi

It seems that after `v6.0.1` release there is no support for .net core 2.2 anymore. Project file should probably target more than one SDK

**Comment by nabinked** [comment]
Please use v5 for 2.2 support

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Hamed Saeedi <notifications@github.com>
पठाइयो: Saturday, November 16, 2019 11:57:11 PM
प्रापक: nabinked/NToastNotify <NToastNotify@noreply.github.com>
बोधार्थ: Subscribed <subscribed@noreply.github.com>
विषय: [nabinked/NToastNotify] .NET Core 2.2 issue (#104)


Hi

It seems that after v6.0.1 release there is no support for .net core 2.2 anymore. Project file should probably target more than one SDK
