### ISSUE TITLE
Weird link when ViewComponent is rendered

### ISSUE THREAD

**Issue by grayniall** [nabinked/NToastNotify#109]
Hello,

Just upgraded to the latest version and I am running on DotNetCore 3.1. When the viewcomponent loads i end up with a url like "_content/NToastNotify/toastr.js?something" which obviously doesn't exist. Noticed that in my prod version the link is something like 

src="/NToastNotify/js/dist/toastr.js?v=201908050838"
and the new version is 
src= "_content/NToastNotify/toastr.js?something"

Any ideas?

Thanks

**Comment by dotnetshadow** [comment]
@grayniall I'm having a similar issue? Did you solve this somehow?
