### ISSUE TITLE
Missing ~ before script src in view Default

### ISSUE THREAD

**Issue by ldkxxx** [nabinked/NToastNotify#112]
Hello, from version 6+, in the view:
\Views\Shared\Components\NToastNotify\Default.cshtml
the ~ before script src is missing, so you can't deploy the web application in a server subfolder.

v6+
`<script src="@Model.LibraryJsPath"></script>`

v5
`<script src="~/NToastNotify/js/dist/@(Model.LibraryDetails.VarName).js?v=@Model.Hash"></script>`

Can you fix it, please?
Thank You

**Comment by nabinked** [comment]
Could you make a quick PR for this please, I may not have enough time to get to fixing this.

**Comment by nabinked** [comment]
Fixed with #116
