### ISSUE TITLE
Change the ILibraryOptions base type from interface to an abstract class.

### ISSUE THREAD

**Issue by kiapanahi** [nabinked/NToastNotify#113]
Since the `ILibraryOptions` is just a base type for `AddXXXToastMessage` methods, it could be converted to an abstract class (e.g. `LibraryOptions`) with two implementations for **Noty** and **Toastr** library-specific options.

Although this is not JAVA and us C#/.NET developers tend to use interfaces as base types a lot, we could adhere to the object oriented principle and the **is-a** rule to maintain that:
 1. `ToastOptions` **is-a** `LibraryOptions`
 2. `NotyOptions` **is-a** `LibraryOptions`

and none of them are actually **implementing** the _behaviors_ of `ILibraryOptions`.

I think this would be a general design improvement of this library :)

**Comment by nabinked** [comment]
Published https://www.nuget.org/packages/NToastNotify/6.0.3
