### ISSUE TITLE
6.0.2 - Razor Pages Project - OnGet works but OnPost doesn't show it on redirect

### ISSUE THREAD

**Issue by talksik** [nabinked/NToastNotify#117]
@nabinked I have a similar problem. using 6.0.2 in netcoreapp3.1 razor pages project

![image](https://user-images.githubusercontent.com/19339529/77128481-81061500-6a0d-11ea-846f-b1abb7df6278.png)

![image](https://user-images.githubusercontent.com/19339529/77128491-86635f80-6a0d-11ea-94d0-84c4c44e63a8.png)

I had to manually put _content/NToastNotify/toastr.js as otherwise, I got 404 error when the viewcomponent for ntoastnotify was trying to do ntoastnotify.init.

![image](https://user-images.githubusercontent.com/19339529/77128551-b7dc2b00-6a0d-11ea-86b0-169bf0265e0d.png)

So with the above in mind, I got the onGet to add a toast message and then it shows on page load. However, when I add a toast onPost, it fails to show the toast on the next page, as it used to when I used netcoreapp2.2 with an older version of NToastNotify nuget package.

Please let me know if you know what the issue could be.

_Originally posted by @talksik in https://github.com/nabinked/NToastNotify/issues/84#issuecomment-601487117_

**Comment by nabinked** [comment]
duplicated by #122
