### ISSUE TITLE
Show toast again when back browser

### ISSUE THREAD

**Issue by daivph** [nabinked/NToastNotify#123]
In Controller
```
//Home View
public IActionResult Index()
        {
            return View();
        }

//Privacy View
        public IActionResult Privacy()
        {
            _toastNotification.AddAlertToastMessage("You will be redirected");
            _toastNotification.AddInfoToastMessage("You got redirected");
            return View();
        }

//Action back to home
        public IActionResult BackHome()
        {
            _toastNotification.AddAlertToastMessage("You will be redirected");
            _toastNotification.AddInfoToastMessage("You got redirected");
            return RedirectToAction("Index");
        }
```
Privacy View

`<a href="/Home/BackHome">Back HOME</a>`

Step:
1- Click menu to Redirect to view Privacy
2. Click a element to back to Home
3. Click menu to Redirect to view Privacy
4. Click back browser button => Not show toast is TRUE ( but this toast is show again)

Toast message maybe cache. Is this bug????
Source: https://github.com/daivph/Test

**Comment by nabinked** [comment]
It cached by the browser. try doing the same step with `Disable Cache` on  in the dev tools. Won't happen
![image](https://user-images.githubusercontent.com/7703179/87103578-c8543200-c298-11ea-9f19-26dcc4211d2e.png)
