### ISSUE TITLE
Is it possible to set the path to toastr.js? Or set it relative?

### ISSUE THREAD

**Issue by petertirrell** [nabinked/NToastNotify#125]
I have an app that I am supporting that was recently upgraded to .NET Core 3.1 and I am getting a new error where it can't find the toastr.js file.  It was previously using NToastNotify 5.0.9, I upgraded that to 6.1.3.  My application sits under a subfolder from root on my site, and I'm getting a 404 error when it tries to load toastr.js.  It looks like the code snippet is coming from the output of `@await Component.InvokeAsync("NToastNotify")` and is building the code location of `<script src="/_content/NToastNotify/toastr.js?something"></script>`.  In my case, that path should be relative to my application, not the site root.  

Is it possible to specify the path to be relative or something?  It looks like one of the PRs possibly might address what I'm running into (https://github.com/nabinked/NToastNotify/pull/116) I also had to manually create the folder structure and copy toastr.js as described in this issue (https://github.com/nabinked/NToastNotify/issues/122).

Thanks for any help!

**Comment by nabinked** [comment]
merged #116 should fix your issue now.
