### ISSUE TITLE
[BUG] Asp.net core 3.1 notification does not work from edit method in controller

### ISSUE THREAD

**Issue by davidbuckleyni** [nabinked/NToastNotify#130]
I am trying to have a toast popup when the user is clicking save however it is not working.

       // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Title,Priority,Subject,MISPrioritysId,IncidentDated,DateRiased,Summary,Notes,Priroty,Category,Type,OMC_1,OMC_2,LastUpdatedBy,Description")] MISObject mISObject) {

            if (ModelState.IsValid) {
                _context.Add(mISObject);
                await _context.SaveChangesAsync();
                _toastNotification.AddAlertToastMessage($"Case has been saved case id is {mISObject.Id}");

                return RedirectToAction("Edit", new { id = mISObject.Id });

            } else {

                return View(mISObject);
            }

            

        }

**Comment by nabinked** [comment]
Works fine. See example https://noty.azurewebsites.net/Privacy 
NOTE: must ACCEPT the cookie policy.
