### ISSUE TITLE
[Documenation] There is no styling information in docs

### ISSUE THREAD

**Issue by davidbuckleyni** [nabinked/NToastNotify#131]
Their is no hints and tips on how we style the toast while it does appear its very plane looking

**Comment by nabinked** [comment]
This library does not look after the styling of toasts. You can override the default styling provided by toast or Noty, whichever you are using by adding custom css rules.

**Comment by davidbuckleyni** [comment]
U have provided no links so can complete this and close this can you at lest provide some samples plz
