### ISSUE TITLE
Supports .NET Core 3.1.7

### ISSUE THREAD

**Issue by ArminShoeibi** [nabinked/NToastNotify#135]
Hello, is this package supports ASP.NET Core 3.1.7 ?
Thanks

**Comment by nabinked** [comment]
Fell free to throw up a PR 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Armin Shoeibi <notifications@github.com>
पठाइयो: Monday, August 24, 2020 11:11:39 PM
प्रापक: nabinked/NToastNotify <NToastNotify@noreply.github.com>
बोधार्थ: Subscribed <subscribed@noreply.github.com>
विषय: [nabinked/NToastNotify] .NET Core 3.1.7 (#135)


Hello, Please update this package for .NET Core 3.1.7
Thanks

**Comment by davidbuckleyni** [comment]
It works fine for me in 3.1.7 what issue are u having @ArminShoeibi

**Comment by ArminShoeibi** [comment]
> 
> 
> It works fine for me in 3.1.7 what issue are u having @ArminShoeibi

I Checked that too, and its working fine.
