### ISSUE TITLE
Is it possible to override the ScriptSrc to point to a local js library?

### ISSUE THREAD

**Issue by petertirrell** [nabinked/NToastNotify#138]
Specifically for toastr, is it possible to specify to use a local copy of toastr.js rather than have it retrieve it from the CDN?  Thanks,

**Comment by nabinked** [comment]
Yes. Pass in your `NToastNotifyOption` with the desired `ScriptSrc` while adding the service.
https://github.com/nabinked/NToastNotify/blob/master/src/Libraries/Toastr/ToastrStartupExtension.cs

**Comment by hakankucuk** [comment]
Please sjow use an simple example. 
Below code gives error,

 services.AddControllersWithViews()
                    .AddNToastNotifyToastr(new ToastrOptions()
                    {
                        ProgressBar = false,
                        PositionClass = ToastPositions.BottomCenter,
                        ScriptSrc = "~/css/toastr.js"                         
                    })

**Comment by hakankucuk** [comment]
Ok. I fixed.

services.AddControllersWithViews()
                    .AddNToastNotifyToastr(new ToastrOptions()
                    {
                        ProgressBar = false,
                        PositionClass = ToastPositions.BottomCenter                         
                    }, new NToastNotifyOption()
                    {
                        ScriptSrc = "/lib/plugins/NToastNotify/toastr.min.js",
                        StyleHref = "/lib/plugins/NToastNotify/toastr.min.css"
                    })

**Comment by dotnetshadow** [comment]
@hakankucuk how did you end up fixing this, it seems that the latest version always loads `/_content/NToastNotify/toastr.js`, even though I set another script path

**Comment by hakankucuk** [comment]
services.AddControllersWithViews()
                    .AddNToastNotifyToastr(new ToastrOptions()
                    {
                        PositionClass = ToastPositions.TopRight                         
                    },
                                           new NToastNotifyOption()
                    {
                        ScriptSrc = "/lib/plugins/NToastNotify/toastr.min.js",
                        StyleHref = "/lib/plugins/NToastNotify/toastr.min.css"
                    });

**Comment by hakankucuk** [comment]
The version is toastr v2.1.3
