### ISSUE TITLE
Toastr.js not found

### ISSUE THREAD

**Issue by raynebair** [nabinked/NToastNotify#155]
I updated to version 8 when I updated my project to .NET 6 and now I'm getting an error message saying toastr.js not found. I've removed the package from my project, then re-added, but I'm still getting the error when I debug my app.

**Comment by raynebair** [comment]
A little more info...the file it's not finding is `/_content/NToastNotify/toastr.js?8.0.0.0`.

**Comment by raynebair** [comment]
For some reason, specifying my own toastr files (ScriptSrc/StyleHref) in the options got it working.

**Comment by Kalyanasis-Sahu** [comment]
Hi @raynebair ,
I am getting the same issue as you do even if I changed the JS and CSS to the local path as you mentioned.Can you share your program.cs or help us out?

**Comment by raynebair** [comment]
@Kalyanasis-Sahu Here's how I got it working in my project:

![image](https://user-images.githubusercontent.com/2170122/194856138-1d74bb9e-0059-4693-b36f-296d32686add.png)

**Comment by Kalyanasis-Sahu** [comment]
We did the same and still have the same issue.Can I know what is the order of the middlewares in your solution.
for us it is 
![image](https://user-images.githubusercontent.com/115451834/195286194-68aeeb60-809a-4931-9a66-6542552e72ca.png)

**Comment by raynebair** [comment]
Ours looks similar. I don't see anything different in the order that would cause it to not work.

![image](https://user-images.githubusercontent.com/2170122/195354830-0ab113d6-59c7-415f-a1db-14783aa6805c.png)
