### ISSUE TITLE
/_content/NToastNotify/toastr.js?8.0.0.0 not found in Production after .net6 upgrade

### ISSUE THREAD

**Issue by Kalyanasis-Sahu** [nabinked/NToastNotify#160]
Hi @nabinked  :
We upgraded to 8.0.0 version while we were upgrading to .net 6 and started getting the error /_content/NToastNotify/toastr.js?8.0.0.0 not found. We tried changing the styleHref and ScriptSrc to local machine, uninstalled and re installed the new version without any luck.
![image](https://user-images.githubusercontent.com/115451834/194814755-e592bdc0-720a-42d2-ad86-7c029814476c.png)

Our Middlewares are in the below order
![image](https://user-images.githubusercontent.com/115451834/194815042-0ae3bb3f-fea5-4865-8acd-411f7cdb1077.png)

This happens only in PROD environment and locally it works.

**Comment by nabinked** [comment]
Where do the actual requests to get the toastr js/css file go from the browser ?

**Comment by Kalyanasis-Sahu** [comment]
If we do not mention any local path, it tries to go to CDN. We tried adding local paths and still we get the same error.

![image](https://user-images.githubusercontent.com/115451834/195281611-d46e34d7-5d17-4331-be20-b6e72ede5087.png)
 The problem is the folder path _content/NToastNotify/toastr.js?8.0.0.0 doesn't get created.

**Comment by nabinked** [comment]
Can you check the sample folder in the repo and see how that is working?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amir3164** [comment]
I have exactly the same problem

**Comment by Kalyanasis-Sahu** [comment]
@amir3164 Please check that , when you publish your package, you are doing it from the right folder .Our problem was we were publishing from the root of the solution, and wwwroot folder will not have the required _content folder there.Only after you publish your artifacts, then push the dlls from there, you will see the _content folder is getting created and the notifications will start apprearing.
