### ISSUE TITLE
Can't see Toastr notifications on all return IActionResult actions except Ok actionresult

### ISSUE THREAD

**Issue by FrancisChung** [nabinked/NToastNotify#18]
Hi,
I'm having some issues with NToastNotify. 
I only seem to be able to get Toastr notifications if I return a Ok object.
I've tried returning other objects such as View and CreateAtRoute but they don't seem to work.

I'm using 1.0.6 of NToastNotify as I assume any higher versions require version 2 or higher of  .NET Core.

Here's one of my functions that use NToastNotify

```
        [HttpPost]
        public IActionResult Create([FromBody] ConfiguredProcess item)
        {
            if (item == null)
            {
                _toastNotification.AddToastMessage("Process Config Creation", "Blank Process details passed", ToastEnums.ToastType.Error);
                return BadRequest();
            }

            try
            {
                item.Id = 0;
                _repository.Add(item);
                _toastNotification.AddToastMessage("Process Config Creation", "Process Config created successfully",
                    ToastEnums.ToastType.Success);
                //return CreatedAtRoute("GetWorkflow", new { id = item.Id }, item); //Doesn't work for Toastr
                return Ok(Json(item));    //Works
                //return View("Index");     // Doesn't work for Toastr
                //return View();            // Doesn't work for Toastr
            }
            catch (Exception ex)
            {
                _toastNotification.AddToastMessage("Process Config Creation Error", ex.ToString(), ToastEnums.ToastType.Error);
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }

        }
```

What could I be doing wrong or have I set up NToastNotify incorrectly?

```
            // ToastNotify() has to be above AddMvc()
            services.AddNToastNotify(new ToastOption()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.BottomCenter
            });

            // Add framework services.
            services.AddMvc();
```

As a test, I've included the following JS on my index.cshtml to prove that verify toastr is up and running.

```
    <script>
        $(function () { //ready
            toastr.info('If all three of these are referenced correctly, then this should toast should pop-up.');
        });
    </script>
```

**Comment by nabinked** [comment]
What net core target framework version you are using? netcoreapp1.1  or  netcoreapp1.0?

**Comment by nabinked** [comment]
Can you upgrade to version 2.0.3 and see if the problem persists ? because version 1.0.6 and 2.0.3 hava same target dependency. So there should not be any issue

**Comment by FrancisChung** [comment]
.net core 1.1

I can try upgrading NToastNotify to 2.0.3 and post my findings here.

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.2",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Cors": "1.1.2",
    "Microsoft.AspNetCore.Diagnostics": "1.1.2",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.2",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.2",
    "Microsoft.AspNetCore.Mvc": "1.1.3",
    "Microsoft.AspNetCore.Mvc.Formatters.Xml": "1.1.3",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.2",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.2",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.2",
    "Microsoft.AspNetCore.StaticFiles": "1.1.2",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.2",
    "Microsoft.Extensions.Logging": "1.1.2",
    "Microsoft.Extensions.Logging.Debug": "1.1.2",
    "Microsoft.EntityFrameworkCore": "1.1.2",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.2",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.2",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.2",
    "Microsoft.Extensions.Configuration.Json": "1.1.2",
    "Microsoft.Extensions.Logging": "1.1.2",
    "Microsoft.Extensions.Logging.Console": "1.1.2",
    "Microsoft.Extensions.Logging.Debug": "1.1.2",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.2",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.1",
      "type": "build"
    },
    "NLog.Web.AspNetCore": "4.3.0",
    "NToastNotify": "1.0.6",
    "WebApiRouteDebugger": "1.0.0",
    "bootstrap": "3.3.7"
  },

  "tools": {
    "BundlerMinifier.Core": "2.4.337",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.1"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config",
      "nlog.config"
    ]
  },

  "scripts": {
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  }
}

```

**Comment by nabinked** [comment]
Let me know what issue you have after the update

**Comment by nabinked** [comment]
Fixed ?

**Comment by FrancisChung** [comment]
I've updated to 2.0.3. 
It's now showing a "Header Request Too Long" errors some times during testing. 

I've observed the following :
1) What I said about only working for Ok object was incorrect. It only seems to work when I refresh the page.
2) I was getting some "Header Request too long" errors if I performed some actions that were firing off AddMessage() calls in the background and no messages were being shown.
3) It looks to me that the messages are being queued up in the background and it only fires off if I load/reload a page. Is there any way of manually forcing the messages to fire?

**Comment by nabinked** [comment]
Yes thats true. This is for server side rendered pages. Which means if you are making ajax request instead of normal request, there is no way this library can render HTML and show you toast messages. In other words, this wont work with ajax request. If you want to show toast messages in ajax requests then simply use the toastr library in the client side to show toast messages.

**Comment by nabinked** [comment]
I will however have to look at "Header Request too long" error. See if I can reproduce and find out whats causing it

**Comment by FrancisChung** [comment]
Thanks for the quick responses so far. 
I suspected that was the case re: server pages + ajax request.
I will just force a reload of the server side pages.

FYI, I wasn't getting those _Header Request Too Long_ error messages in 1.0.6.

**Comment by nabinked** [comment]
Nice. I will have to look into it. Would be great, if you could create a new issue for the "Header Request Too Long" error.

**Comment by luigi108** [comment]
Hi, 

First of all, I apologize for English, I'm Latin, I've been trying to make it work for a week, but I have the same problem as FrancisChung, I use net core 1.1.3 and NToastNotify 2.0.3. and I do not use ajax all the requests are normal; Thanks for the `help`

**Comment by luigi108** [comment]
Hi,

I get the following error message
``
{"title":"Success title specified in controller action","message":"Same for success message","toastType":0,"toastOptions":null},{"title":"Success","message":"Overwritten default success message","toastType":0,"toastOptions":null},{"title":"Info","message":"This is an information notification.","toastType":2,"toastOptions":null},{"title":"Warning","message":"This is a warning notification.","toastType":1,"toastOptions":null},{"title":"Error","message":"Task could not complete successfully.","toastType":3,"toastOptions":null},{"title":"Custom Title","message":"My Custom Message","toastType":0,"toastOptions":{"tapToDismiss":null,"toastClass":null,"containerId":null,"debug":null,"showMethod":null,"showDuration":null,"showEasing":null,"onShown":null,"hideMethod":null,"hideDuration":null,"hideEasing":null,"onHidden":null,"closeMethod":null,"closeDuration":null,"closeEasing":null,"closeOnHover":null,"extendedTimeOut":null,"iconClass":null,"positionClass":"toast-bottom-left","timeOut":null,"titleClass":null,"messageClass":null,"escapeHtml":null,"target":null,"closeHtml":null,"closeClass":null,"newestOnTop":null,"preventDuplicates":null,"progressBar":null,"rtl":null,"closeButton":null,"onclick":null,"successTitle":null,"successMessage":null,"infoTitle":null,"warningTitle":null,"errorTitle":null,"errorMessage":null}}]``

**Comment by nabinked** [comment]
Can you give me steps to reproduce your issue?

**Comment by luigi108** [comment]
file _layout.cshtml

@using Microsoft.AspNetCore.Identity


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - Admin-Panel</title>*@
    <title>Admin-Panel </title>

    @*<link rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css" />*@
    @*<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">*@

    <link type="text/css" rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css"    media="screen,projection"/>
 
    <link  href="~/lib/mystyle/miestilo.css" rel="stylesheet" />

    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
  
</head>
<body>
<header>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper purple z-depth-3">
                <a href="#" class="brand-logo center">Admin-Panel</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                
                <ul class="left hide-on-med-and-down">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="material-icons left ">home</i>Home</a></li>
                    <li><a asp-area="" asp-controller="Role" asp-action="Index"><i class="material-icons left">group</i>Roles</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Listado"><i class="material-icons left">person</i>Usuarios</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact"><i class="material-icons left">assignment</i>Accesos</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")

             
                @*<a class="button-collapse" href="#" data-activates="nav-mobile">
                    <i class="material-icons">menu</i>
                </a>*@

                @*<ul id="nav-mobile1" class="right hide-on-med-and-down">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="material-icons left ">home</i>Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="material-icons left">person</i>Roles</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About"><i class="material-icons left">group</i>Usuarios</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact"><i class="material-icons left">group</i>Accesos</a></li>
                    @await Html.PartialAsync("_LoginPartial")
     
                </ul>*@
    
            </div>
        </nav>
    </div>

</header>
<main>
    @RenderBody()
    
  
</main>
   

<footer class="page-footer purple">
    <div class="footer-copyright">
        <div class="container center">
             Copyright &copy; 2017 - Todos los derechos reservados
        </div>
    </div>
</footer>


<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/materialize/dist/js/materialize.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

<script src="~/js/site.js"></script>

<script src="~/lib/toastr/toastr.js"></script>



@await Component.InvokeAsync("NToastNotify.Toastr")


@RenderSection("scripts", required: false)
    

</body>
</html>

***** file index.cshtml (homecontroller)
@using System
@using NToastNotify
@inject IToastNotification ToastNotification


@{
    ViewData["Title"] = "Home Page";
}
<h1 class="center">Home</h1>
@if (User.Identity.IsAuthenticated)
{
    <h1>Welcome back @User.Identity.Name</h1>
    <h2>User Claims</h2>
    <dl>
        @foreach (var claim in User.Claims)
        {
            <dt>@claim.Type</dt>
            <dd>@claim.Value</dd>
        }
    </dl>

    var authScheme = "Identity.Application";
    if (!String.IsNullOrWhiteSpace(authScheme))
    {
        <h2>Cookies Properties</h2>
        <dl>
            @{
                var props = (await Context.Authentication.GetAuthenticateInfoAsync(authScheme)).Properties;
            }
            @foreach (var item in props.Items)
            {
                <dt>@item.Key</dt>
                <dd>@item.Value</dd>
            }
        </dl>
    }
 }

@Html.Raw(Json.Serialize(ToastNotification.PeekToastMessages()))

**Comment by luigi108** [comment]
file startup.cs

       public void ConfigureServices(IServiceCollection services)
        {
           // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("CnxLocalAuth")));

            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            // para la confirmacion de email
            //services.AddIdentity<ApplicationUser, IdentityRole>(config =>
            //{
            //    config.SignIn.RequireConfirmedEmail = true;
            //});


            // configiracion de toast
            //services.AddNToastNotify();
            services.AddNToastNotify(new ToastOption()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.BottomCenter
            }, new NToastNotifyOption()
            {
                SuccessMessage = "Overwritten default success message"
            });

            services.AddMvc();

            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

            // identityServer 
            services.AddIdentityServer()
               .AddTemporarySigningCredential()
                .AddInMemoryPersistedGrants()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddAspNetIdentity<ApplicationUser>();
        }

**Comment by nabinked** [comment]
Please look at the sample [project](https://github.com/nabinked/NToastNotify/tree/master/sample/NToastNotify.Web) in this repo for reference

**Comment by luigi108** [comment]
Hi,

I have seen the example and I see that it is just as it is in my solution; I have removed everything and reinstalled from nuget and added the code to the Startup, HomeController and Index files and it still does not work but I have seen that the code @await Component.InvokeAsync ("NToastNotify.Toastr") shows me marked in red "(NToastNotify.Toastr) Also I notice in the example that NToastNotify is not in dependencies of the Nuget, it is taking it from the reference of the project NtoasNotify.

Thanks for the help.

**Comment by luigi108** [comment]
Hi,

I forgot, the example is with core 2.0 and I work with core 1.1

**Comment by luigi108** [comment]
Hi

I have continued with the tests, I have created a new project and appear toast but with message on the screen, I attached the image. It is configured exactly like my production project the differences is that my project of proudccion does not use bootstrap uses metalize and I have the libraries of IdentityServer, apparently does not work with these last two libraries, but in new project follows with the messages in the body of the Web. 
I also attached the new project with the error.
Any solution
![toast](https://user-images.githubusercontent.com/31579622/30005237-86cfc800-90a3-11e7-8355-3dda3a5f3ec4.jpg)

[ToastServer.zip](https://github.com/nabinked/NToastNotify/files/1273087/ToastServer.zip)

**Comment by nabinked** [comment]
Everything seems to be working fine. PeekMessages is meant to see what messages has been added so far in the list of toast messages. It does not render a toast message in the ui.

**Comment by luigi108** [comment]
Thanks for everything, but it definitely does not work if I have materialize and identityserver, because in a new project without these 2 libraries it works correctly.

**Comment by luigi108** [comment]
Hi,
The problem is definitely with the IdentityServer4, when using the interface IIdentityServerInteractionService does not work NToastNotify; unfortunately I will have to find another alternative for toast, thanks for the help and sorry for the inconvenience.

**Comment by nabinked** [comment]
No worries. Good Luck
