### ISSUE TITLE
Error 404 with /NToastNotify/js/dist/toastr.js.map

### ISSUE THREAD

**Issue by JhobanyPena** [nabinked/NToastNotify#26]
I getting this error is some occasions... it can't find the .map file!
The funny topic here is that i don't have this directory on my solution... i have other '\wwwroot\vendors\bower_components\toastr'.

Any ideas?

{
  "name": "Microsoft.ApplicationInsights.Dev.Request",
  "time": "2018-02-27T14:19:22.1554123Z",
  "tags": {
    "ai.internal.sdkVersion": "aspnet5c:2.1.1",
    "ai.application.ver": "3.4.0.0",
    "ai.internal.nodeName": "DESKTOP-DEV",
    "ai.location.ip": "::1",
    "ai.cloud.roleInstance": "DESKTOP-DEV",
    "ai.operation.name": "GET /NToastNotify/js/dist/toastr.js.map",
    "ai.operation.id": "1176b267-400a63c996f478ff"
  },
  "data": {
    "baseType": "RequestData",
    "baseData": {
      "ver": 2,
      "id": "|1176b267-400a63c996f478ff.",
      "name": "GET /NToastNotify/js/dist/toastr.js.map",
      "duration": "00:00:00.0007341",
      "success": false,
      "responseCode": "404",
      "url": "https://localhost:44379/NToastNotify/js/dist/toastr.js.map",
      "properties": {
        "httpMethod": "GET",
        "AspNetCoreEnvironment": "Development",
        "DeveloperMode": "true"
      }
    }
  }
}

Regards,

**Comment by nabinked** [comment]
The js file is coming from embedded view inside the library so you won't find it in your web folder. Any particular case when this happens or it happens randomly?

**Comment by JhobanyPena** [comment]
This behaviour is randomly... Do you need anything else?

**Comment by nabinked** [comment]
Temporary solution would be to put an empty toastr.js.map at the same exact path in your wwwroot folder.

I will push a new version with a more permanant solution.

**Comment by JhobanyPena** [comment]
Awesome Nabin! I will implement this temporary solution on my project!
I will be waiting for the new version! Thanks! :)
