### ISSUE TITLE
AddNToastNotify Extension Method on IMvcCoreBuilder

### ISSUE THREAD

**Issue by paulyipkh** [nabinked/NToastNotify#27]
I am working on a code base using MvcCore rather than Mvc. Can an extension method be added based on IMvcCoreBuilder as well ?

**Comment by paulyipkh** [comment]
Will do so when I find the time.

**Comment by nabinked** [comment]
I have included that in the noty branch. Will merge to master soon

**Comment by paulyipkh** [comment]
Thanks a lot.

**Comment by nabinked** [comment]
added on 5.0.0
