### ISSUE TITLE
SimpleInjector error > IToastNotification that is not registered

### ISSUE THREAD

**Issue by virnik** [nabinked/NToastNotify#29]
> System.InvalidOperationException: 'The configuration is invalid. Creating the instance for type ProfileController failed. The constructor of type ProfileController contains the parameter with name 'toastNotification' and type IToastNotification that is not registered. Please ensure IToastNotification is registered, or change the constructor of ProfileController.'

`container.Register<IToastNotificatio,ToastNotification>();`
or
`container.CrossWire<IToastNotification>(app);`
Does not help.

How use NToastNotify with Simple Injector?

**Comment by virnik** [comment]
No, I only tried use ToastNotifier with Simple Injector without any modifications.

**Comment by nabinked** [comment]
closing this as it is out of scope of this project
