### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.Win32.Registry

### ISSUE THREAD

**Issue by nabinked** [nabinked/NToastNotify#31]
[Issue in dotnet SDK](https://github.com/dotnet/core-setup/issues/2113)

**Comment by nabinked** [comment]
Solution : https://github.com/dotnet/core-setup/issues/2113#issuecomment-337341068

**Comment by KennethInfoEasy** [comment]
I get this issue after adding the ntoastynotify

**Comment by nabinked** [comment]
Add this to your web project's csproj file.

<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>

You can put it after the TargetFramework tag. 
See the solution I mentioned in the comment above for more details.

**Comment by KennethInfoEasy** [comment]
Thank you for your quick reply.  Will try it.
