### ISSUE TITLE
Why removing option to specify custom title on each notification?

### ISSUE THREAD

**Issue by os1r1s110** [nabinked/NToastNotify#32]
As the title says, I would like to know the motivation behind the removal of the optional title attribute on IToastNotification?

Thanks in advance!

**Comment by nabinked** [comment]
The reason behind the removal of the optional title argument was made in order to support noty which does not have the notion of title at all. So, now each method on the IToastNotification interface simply takes a message and options. However if you want to specify a custom title for each notification type you can specify it during startup using Default[type]Title attribute in NToastNotfyOptions which will be applied for all the notifications which makes sense because normally its the message which changes but not the title. I am not sure if thats the right way to do it but feel free to advise if there are better ways to do it.

**Comment by os1r1s110** [comment]
In my case I appreciated the possibility to customize the title for example to give more variations for each type of notification.

For example, if a user makes a small mistake that results in an error (more important than a warning but not a critical error for example) I liked to be able to put the error message title as something like "Oops" instead of the more formal "Error".

In other cases the standard error title is perfect, hence why the appreciation of the title modification per notification. 

I understand though that you want to support more libraries which might not all support the same options so I will use a generic notification title for now.
Thanks is for the clarification

**Comment by nabinked** [comment]
Your concern is absolutely valid. I can see the necessity to have custom title now. 
Since we already have an options object, how about we simply add whatever property is needed to the options class on top of the library options. So now the ToastOptions class will be a super class of ToastJsOptions. This way we can have any custom properties on ToastOptions class and the necessary js library options in the base class. This sound like a very extensible approach so if in future we have any new properties from any library we can simple add the property in the Super Options class and would not affect anything.  I am not sure if I got my message across effectively. But do let me know what you think.

**Comment by os1r1s110** [comment]
Ok so you would add all options that are not common to all plugins s supported in a kind of "options holder" which every plugin could use at will ? 

Another option might be to group all common plugins options within a base class and then create a new class inheriting this for each plugin so that you can use the specific option s whenever required and the generic ones when you don't need to specify any particular setting....? 

What would you think would be the best approach? And if anyone else has an idea I, I would be interested in hearing it.

**Comment by nabinked** [comment]
Proposed solutions:

Any js library specific options will have an interface that will purely represent the library specific options
Like for example for toastrjs
```c#
    /// <summary>
    /// Purely mirrors the options object used by toastr.js library
    /// </summary>
    interface IToastrJsOptions
    {
        bool? TapToDismiss { get; set; }
        string ToastClass { get; set; }
        string ContainerId { get; set; }
        bool? Debug { get; set; }
        string ShowMethod { get; set; }
        int? ShowDuration { get; set; }
        string ShowEasing { get; set; }
        string OnShown { get; set; }
        string HideMethod { get; set; }
        int? HideDuration { get; set; }
        string HideEasing { get; set; }
        string OnHidden { get; set; }
        bool? CloseMethod { get; set; }
        bool? CloseDuration { get; set; }
        bool? CloseEasing { get; set; }
        bool? CloseOnHover { get; set; }
        int? ExtendedTimeOut { get; set; }
        /// <summary>
        /// Use the <see cref="IconClasses"/> to set the available values
        /// </summary>
        string IconClass { get; set; }
        /// <summary>
        /// Use the <see cref="ToastPositions"/> to set the available values
        /// </summary>
        string PositionClass { get; set; }
        int? TimeOut { get; set; }
        string TitleClass { get; set; }
        string MessageClass { get; set; }
        bool? EscapeHtml { get; set; }
        string Target { get; set; }
        string CloseHtml { get; set; }
        string CloseClass { get; set; }
        bool? NewestOnTop { get; set; }
        bool? PreventDuplicates { get; set; }
        bool? ProgressBar { get; set; }
        bool? Rtl { get; set; }
        bool? CloseButton { get; set; }
        string Onclick { get; set; }
    }
```
and then there will be a class that will implemnet this interface and will have custom properties needed to support NToastNotify requirements for example for toastr we will have

```C#
    public class ToastrOptions: IToastrJsOptions, ILibraryOptions
    {
        public bool? TapToDismiss { get; set; }
        public string ToastClass { get; set; }
        public string ContainerId { get; set; }
        public bool? Debug { get; set; }
        public string ShowMethod { get; set; }
        public int? ShowDuration { get; set; }
        public string ShowEasing { get; set; }
        public string OnShown { get; set; }
        public string HideMethod { get; set; }
        public int? HideDuration { get; set; }
        public string HideEasing { get; set; }
        public string OnHidden { get; set; }
        public bool? CloseMethod { get; set; }
        public bool? CloseDuration { get; set; }
        public bool? CloseEasing { get; set; }
        public bool? CloseOnHover { get; set; }
        public int? ExtendedTimeOut { get; set; }
        /// <summary>
        /// Use the <see cref="IconClasses"/> to set the available values
        /// </summary>
        public string IconClass { get; set; }
        /// <summary>
        /// Use the <see cref="ToastPositions"/> to set the available values
        /// </summary>
        public string PositionClass { get; set; }
        public int? TimeOut { get; set; }
        public string TitleClass { get; set; }
        public string MessageClass { get; set; }
        public bool? EscapeHtml { get; set; }
        public string Target { get; set; }
        public string CloseHtml { get; set; }
        public string CloseClass { get; set; }
        public bool? NewestOnTop { get; set; }
        public bool? PreventDuplicates { get; set; }
        public bool? ProgressBar { get; set; }
        public bool? Rtl { get; set; }
        public bool? CloseButton { get; set; }
        public string Onclick { get; set; }

        //Non library options
        string Title { get; set; }
        
        //ILIbraryoptions
        string ILibraryOptions.Json => this.ToJson();
    }
```

This way when we have the need to add any new options we can simply add it on the class not on the interface and we can understand that these are custom values.

Usage on IToastNotification interface would be like this
```c#
_toastNotification.AddErrorToastMessage("Custom Error Message", new ToastrOptions() { Title = "Oops" });

```

**Comment by os1r1s110** [comment]
That seems like a good idea to me :) Pretty extensible too.
