### ISSUE TITLE
Error 400 with NToastNotify.ts line 139 if not call, Error 500 if call

### ISSUE THREAD

**Issue by camambeou** [nabinked/NToastNotify#35]
I have implement successfully NToastNotify in my project (.Net Core 2.0.6 MVC). The messages are shown as expected on my Views. However, it got error 400 in case of using partial view, called via Ajax (POST and GET), if I comment my code calling NToast messages. I got error 500 if I used code calling NToast message.
My action is below, example for POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNewDep([FromForm]DepViewModel model)
        {
            SetViewDataStatic();
            if (ModelState.IsValid)
            {
                var isExist = DepManager.Exist(model.DepName);
                if (isExist == true)
                {
                    toastMessage.AddErrorToastMessage($"Dep's name is used. Choose another name");
                    return PartialView(model);
                }
                var newDep = new Dep
                {
                    //.....
                };
                var result = DepManager.InsertNewDep(newDep);
                if (result > 0)
                {
                    SetViewDataDynamic();
                    toastMessage.AddSuccessToastMessage("Successfully done");
                    return PartialView(model);
                }
                else
                {
                    toastMessage.AddErrorToastMessage("Got error! Please try again later!");
                    return PartialView(model);
                }
            }
            return PartialView(model);
        }

**Comment by nabinked** [comment]
What's the stack trace of error?

**Comment by camambeou** [comment]
It simply shows on Console (Chrome): 
NToastNotify.ts:139 POST https://localhost:44396/AdminAccountManagement/EditSelectedDep 400 ()

  | XMLHttpRequest.send | @ | NToastNotify.ts:139
-- | -- | -- | --
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | (anonymous) | @ | site.min.js:1
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

 if I used this line "_toastMessage.AddSuccessToastMessage("Successfully done");_"
And shown:

NToastNotify.ts:139 POST https://localhost:44396/AdminAccountManagement/EditSelectedDep 500 ()

  | XMLHttpRequest.send | @ | NToastNotify.ts:139
-- | -- | -- | --
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | (anonymous) | @ | site.min.js:1
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2
 If I commented that code

**Comment by nabinked** [comment]
I'm not sure if its caused by NToastNotify. It could be some server exception. 400 usually means bad request may be some parameters not provided. 500 means server error some exception on the server you really need to provide the call stack of the server error.

**Comment by camambeou** [comment]
I tried debug it and found the call stack shown:

System.ObjectDisposedException: The response has been aborted due to an unhandled application exception. ---> System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x1EDD
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(String headerCharacters)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(StringValues headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at NToastNotify.NtoastNotifyMiddleware.Callback(Object context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<FireOnStarting>d__197.MoveNext()
Maybe that issue is at non- ASCII in the header. How can I fix it?

**Comment by nabinked** [comment]
Will check this evening.

**Comment by camambeou** [comment]
I have found more issue: the Initiator show "NToastNotify.ts" instead of my ajax function.
Maybe the NToastNotify has overwritten the handler.
Could you fix those soon?

**Comment by nabinked** [comment]
Yes it intercepts all ajax calls. Have you updated to 5.0.0 version yet ?

**Comment by nabinked** [comment]
And regarding  Invalid non-ASCII header value. You may have put some invalid characters in you toast messages.

**Comment by camambeou** [comment]
Thanks for ur support, I have updated NToastNotify to 5.0.3, and still got the same errors. I will try to catch detail of those. Hope finding something clearly

**Comment by camambeou** [comment]
I don't find anything to catch those error.
I give you my some code to check:

1.	My Startup.cs:
using NToastNotify;
services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
            {
                PreventDuplicates = true,
                TimeOut = 2000,
                ProgressBar = false
            },
            new NToastNotifyOption()
            {
                DefaultErrorTitle = "Got an error:",
                DefaultInfoTitle = "Info from system:",
                DefaultSuccessTitle = "Info from system:",
                DefaultAlertTitle = "Warning from system:",
                DefaultWarningTitle = "Warning from system:"
 });
2.	My Controller:
        [HttpGet]
        public IActionResult AddNewDep()
        {
            var model = new DepViewModel() { };
            toastMessage.AddInfoToastMessage("Please confirm this form below");
            return PartialView(model);
        }
3.	My Site.js:
$("#create-dep").click(function (e) {
            e.preventDefault();
            $("#partial-dep").empty();
            ShowWaiting();
            $.ajax({
                url: "AdminAccountManagement/AddNewDep",
                type: "GET",
                dataType: "html",
                success: function (result) {
                    HideWaiting();
                    $("#partial-dep").html(result);
                }
            });
        });
4.	My View:
<div class="col-lg-8 col-md-7 col-sm-12 dep-detail">
        <h5>Detail Informations</h5>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel-dep-detail animated slideInRight">
                    <div class="create-edit-dep">
                        <button id="create-coquan" class="btn btn-primary" type="submit" title="Thêm cơ quan mới">Create new DEP</button>
                    </div>
                    <div id="partial-dep">
                    </div>
                </div>
            </div>
        </div>
    </div>

I don’t use any invalid character in header.

**Comment by camambeou** [comment]
Sorry for all info above. A have implement all case that I need. And the toast is working find.
My issue is language localization. So if requests came from "cn", "vi", ... my webapp automatically changes displayed text depending to language . 
Could you fix the NToastNotify supporting more language text????
