### ISSUE TITLE
View Component not resolving

### ISSUE THREAD

**Issue by scriptmonkey69** [nabinked/NToastNotify#36]
I cannot seem to get the View Component to resolve when I add thwe foolowing line of code to the bottom of the body tag in my layout page.

`@await Component.InvokeAsync("NToastNotify")`

The string "NToastNotify" stays read and I get an error message saying 

> cannot resolve view component

**Comment by nabinked** [comment]
Install and Build. Should work see [sample](https://github.com/nabinked/NToastNotify/blob/master/sample/NToastNotify.Toastr/Views/Shared/_Layout.cshtml)

**Comment by phlall** [comment]
Hi I have the same issue. .Net core 2.0. Layout page in same format as recommended. and installed as per.

**Comment by nabinked** [comment]
You need to install the library and do a project build.

**Comment by phlall** [comment]
Thanks but when you say install library do you mean the Nuget library. In which case I have already done that.
..or download the source and build that then use the .dll? Please clarify

**Comment by nabinked** [comment]
Sorry I meant, download from Nuget.  Follow the steps listed on the [ReadMe](https://github.com/nabinked/NToastNotify/blob/master/README.md) and you should be good to go.
If that does not work can you simple clone this project in your machine. Open the solution in Visual Studio 2017 and set startup project as any one of the sample project and simple run them (Ctrl+f5) and see if you see a sample project run on your browser with toast notification.

**Comment by nabinked** [comment]
Closing this. Please reply if this issue still exists.
