### ISSUE TITLE
Error 500 if toastmessage (text or title) contains characters in another language

### ISSUE THREAD

**Issue by camambeou** [nabinked/NToastNotify#37]
That error came **only in case of using with partial view**. If using with normal view, it works as expected.
Detail error is:

> System.InvalidOperationException: **Invalid non-ASCII or control character in header:** 0x0388
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(String headerCharacters)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(StringValues headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   **at NToastNotify.NtoastNotifyMiddleware.Callback(Object context)**
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<FireOnStarting>d__197.MoveNext()

Tested with some language: CN ("错误已经出现"), VI ("Có lỗi phát sinh"), Greek ("Έχουν προκύψει σφάλματα")
@nabinked Could you support more language? This is awesome!

**Comment by nabinked** [comment]
I have not tested with other languages than English. This may be a a bit hard to achieve. I will have to see what can be done

**Comment by nabinked** [comment]
No I am sorry. This issue is sort of hard to fix.
So this issue does not happen when you are doing a simple page load and showing the toast message. It happens only when you add toast messages on an AJAx request. That is because AJAX request uses custom response headers to pass the toasts messages to the client and unfortunately response headers don't support non ASCII characters at all. And that's the reason for your issue. I will have to come up with a different solution to support your case which may not be easy. if you any ideas to support this feature feel free to suggest. So to may ne a while before this is supported.

**Comment by camambeou** [comment]
I found this:
https://stackoverflow.com/questions/47557607/change-reponse-header-encode-net-core
So you could try to encode header responses at first

**Comment by camambeou** [comment]
Acording to this:
https://github.com/aspnet/HttpAbstractions/issues/971
And this:
https://github.com/aspnet/KestrelHttpServer/issues/2296
Then, the solution I guest is encoding the header responses.
So, could you try that?!

**Comment by nabinked** [comment]
Interesting i will give it a shot and see what happens. Thanks for the research.

**Comment by serralha85** [comment]
For those who are having these issue I've manage to solve it by converting the non ascii characters to the HTML encoding.

For example Ç pass with &ccedil; 

In the toast it will show the correct character.

**Comment by nabinked** [comment]
Hopefully fixed by https://github.com/nabinked/NToastNotify/pull/62
reopen if not
