### ISSUE TITLE
Request header field X-NToastNotify-Request-Type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by mekkerm** [nabinked/NToastNotify#38]
Hello,

I'm facing an issue with NToastNotify. I'm trying to send a CORS ajax request, to get some data from the  elasticsearch server on my local machine, and I discovered that the toastr.js intercepts somehow my requests. I'm pretty sure that this is the cause, because everything works fine when I do not include the client package in the _Layout.cshtml:

await Component.InvokeAsync("NToastNotify")

Here is the error I'm getting:

![image](https://user-images.githubusercontent.com/9267564/38455269-5ffe52c0-3a7e-11e8-9b16-6abcdb3287ec.png)

The JS code I'm running is the following:

    window.esClient = $.es.Client({
        hosts: "http://127.0.0.1:9200/"
    });

    window.esClient.ping({
        requestTimeout: 30000,
    }, function (error) {
        if (error) {
            console.error('elasticsearch cluster is down!');
        } else {
            console.log('All is well');
        }
    });

I'm using jquery and the elasticsearch.js bower packages. 
The local elasticserach server is configured to work with CORS request, so on that side everything is fine:

http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length

**Comment by nabinked** [comment]
Try adding X-NToastNotify-Request-Type to your http.cors.allow-headers

**Comment by mekkerm** [comment]
Thank you for quick answer, I just tried out, and partially solved my problem, my ES requests are not blocked anymore, I'm just getting an "Refused to get unsafe header "X-NToastNotify-Messages" warning in the console, but I can live with it for now. Thank you again!

![image](https://user-images.githubusercontent.com/9267564/38464540-fc2f8bb6-3b17-11e8-9d48-34c6e0140817.png)
