### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'NToastNotify.ToastNotification'.

### ISSUE THREAD

**Issue by hong-duc** [nabinked/NToastNotify#4]
this error happen when it run `@await Component.InvokeAsync("NToastNotify.Toastr")` in layout. Please help!

**Comment by hong-duc** [comment]
I fix it with [SO answer](http://stackoverflow.com/questions/37371264/invalidoperationexception-unable-to-resolve-service-for-type-microsoft-aspnetc)

**Comment by nabinked** [comment]
I think it would be a good idea to \ check while adding NToastNotify to service collection, whether or not the user has already registered an implementation of IHttpContextAccessor and register the dependency.
