### ISSUE TITLE
Error when text contains single quotes (apostrophe)

### ISSUE THREAD

**Issue by os1r1s110** [nabinked/NToastNotify#42]
As the title says, the generated toast notification fails to render correctly if text contains any single quote (which are pretty common in French language) -> similar problem as outlined in #22, could close this one in favor of the former.

Would it be a big problem switching to double quotes for string delimiter?

JavaScript handles it perfectly when text within double quotes contains single quotes. 

Thanks in advance!

**Comment by nabinked** [comment]
The current version seems to have no issues with single quotes. Which version are you on?

**Comment by os1r1s110** [comment]
Right, I stayed behind on purpose when the possibility to customize the notification title easily for each notification was removed (for integrating other toast notifications library I think)

I will update to the latest version and try to figure out a way to customize titles.

**Comment by nabinked** [comment]
5.0.7 has the Title property in ToastrOptions class which you can set to give title to toastr toast messages.

**Comment by os1r1s110** [comment]
Nice, I'll check it out! Was it implemented in a similarly extensible way as you proposed in issue 32? (I will take a look at the code in a couple minutes so don't feel forced to answer that one hehe).

I'll close as it is supported/not an issue in latest version.

**Comment by nabinked** [comment]
Feel free to reopen the issue if it's not resolved.

**Comment by brianpitt** [comment]
I'm going through some tutorials on ASP.NET using .NET Core 3.1, and I just spent a frustrating half-hour tearing my hair out trying to understand why my toast notification didn't work.
A single quote bug??  Seriously??  How did they miss this?!?!
It figures, I always end up getting bit by the stupid bugs that made it to production.  I swear, I should be a tester for literally everyone XD.
