### ISSUE TITLE
InvalidOperationException - Conflit with ViewComponents?

### ISSUE THREAD

**Issue by mmgil** [nabinked/NToastNotify#45]
Hi,

In first place, your project is wonderful. Congratulations.

Everything was working fine. So I needed to add a viewcomponent in the project and CRASH!!!

I created a folder with name ViewComponent.

![image](https://user-images.githubusercontent.com/29230461/41619794-ddb1c86c-73dd-11e8-943a-eccba1e5da34.png)

**Comment by nabinked** [comment]
Interesting. I will have to look at it. The error stack however says that you have a missing method in your view component. Are you sure that's not the case ?

**Comment by mmgil** [comment]
Yeah,

I created one view component with different name of the folder of the View.

Sorry for false positive.
