### ISSUE TITLE
Show message after ajax redirect?

### ISSUE THREAD

**Issue by djordjedjukic** [nabinked/NToastNotify#48]
Hi, is it possible to show message if I redirect to action from ajax. Here is the code:

C# code
`publicIActionResult Ajax()
{
     toastNotification.AddSuccessToastMessage(TextResource.Info_SaveSuccess);
     return this.Ok(new { redirect = true, url = "/User/EditProfile" });
}
`
JS code
`
$.ajax({
        url: $this.attr('action'),
        type: 'post',
        data: formData,
        dataType: 'json',
        statusCode: {
            200: function (data) {               
                if (data.redirect) {
                    if (data.url) {
                             window.location = data.url;
                    } else {
                        window.scrollTo(0, 0);
                        window.location.reload();
                    }
                }
            }
        },
`

**Comment by nabinked** [comment]
I don’t think that’s possible. However you may be able to set a timeout on your Ajax success handler before redirecting to another page. This will show the toast message before redirecting.

**Comment by djordjedjukic** [comment]
I am already using it on that way, but I don't like it. If I set timeout 1-2 seconds message close to fast and if I set timeout more the 3 seconds it looks that redirects takes too long. I will try to use some other solutions.
Thanks any way, great work! :)
