### ISSUE TITLE
Application Insight CORS

### ISSUE THREAD

**Issue by bbakermmc** [nabinked/NToastNotify#49]
When you use Application Insight it throws a cors error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dc.services.visualstudio.com/v2/track. (Reason: missing token ‘x-ntoastnotify-request-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel)

Web Config:
```
 <httpProtocol>
      <customHeaders>
        <remove name="X-Powered-By" />

        <add name="Access-Control-Allow-Origin" value="*"/>
        <add name="Access-Control-Allow-Methods" value="GET,PUT,POST,DELETE,OPTIONS"/>
        <add name="Access-Control-Allow-Headers" value="Content-Type,x-ntoastnotify-request-type"/>
      </customHeaders>
    </httpProtocol>
```

**Comment by nabinked** [comment]
Even with that web.config?

**Comment by bbakermmc** [comment]
Yup.

Sent from my iPhone

On Sep 27, 2018, at 5:18 PM, Nabin Karki Thapa <notifications@github.com<mailto:notifications@github.com>> wrote:


Even with that web.config?

**Comment by nabinked** [comment]
Thats weird. Can you provide  the minimum steps to reproduce this. I should be able to test this weekend.

**Comment by bbakermmc** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-core

Make sure you do this part:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-core#page-view-load-time

**Comment by os1r1s110** [comment]
Just hit the same problem with another web service (Algolia search)

**Comment by jerriep** [comment]
I am running into this same issue. Took me hours to try and figure out why my Application Insights javascript snippet won't work, then tracked it down to NToastNotify.

@nabinked Is there any progress on this? Any reason why NToastNotify is adding that header to requests?

**Comment by nabinked** [comment]
Sorry @jerriep you had to waste so much time on this. The headers are added to track Ajax toast notifications. If you are not doing toast notifications on ajax calls you can safely turn of Ajax calls by setting ‘DisableAjaxToasts’ on startup registration.

**Comment by jerriep** [comment]
@nabinked But I am using Ajax toasts :(

I just had a look at the TypeScript source and it seems the problem is that you are adding that header to all AJAX requests. The problem is that the Application Insights request is also an AJAX call so you are adding it to that, but the AI servers do not recognise that header and therefore the error.

I think there should be a check to only add the header when the AJAX request is to the same domain as the application.

**Comment by nabinked** [comment]
> How can I go about running and debugging your TS locally when I clone your repo?

You can go `npm run start` on the src folder that should build and transpile ts -> js

**Comment by nabinked** [comment]
> @nabinked But I am using Ajax toasts :(
> 
> I just had a look at the TypeScript source and it seems the problem is that you are adding that header to all AJAX requests. The problem is that the Application Insights request is also an AJAX call so you are adding it to that, but the AI servers do not recognise that header and therefore the error.
> 
> I think there should be a check to only add the header when the AJAX request is to the same domain as the application.

That's actually a good point. If you can throw up a PR with that fix, would be great. I haven't been able to look after the issues in this repo for quite some time. Other wise I can have a crack at it this weekend.

**Comment by jerriep** [comment]
@nabinked I created a PR which fixes this. It proved fairly simple, as described in the PR.

Could you please try and get a new release on to Nuget this weekend if you get a chance? 🙏

**Comment by nabinked** [comment]
version 5.0.9 up in Nuget with this fix. Might take a while before its listed though..

**Comment by jerriep** [comment]
Great stuff! I installed it and the issue is now resolved.

Thanks a lot for the quick turnaround on this one @nabinked
