### ISSUE TITLE
v.appendTo is not a function

### ISSUE THREAD

**Issue by gauravbhavsar** [nabinked/NToastNotify#53]
I configured NToastNotify as mentioned in documentation, but I am getting error in browser's console as

> Uncaught (in promise) TypeError: v.appendTo is not a function
    at d (toastr.js:474)
    at n (toastr.js:474)
    at g (toastr.js:474)
    at Object.i [as success] (toastr.js:474)
    at t.showMessage (toastr.js?v=201806070714:1)
    at toastr.js?v=201806070714:1
    at Array.forEach (<anonymous>)
    at t.e.showMessages (toastr.js?v=201806070714:1)
    at t.<anonymous> (toastr.js?v=201806070714:1)
    at toastr.js?v=201806070714:1
d @ toastr.js:474
n @ toastr.js:474
g @ toastr.js:474
i @ toastr.js:474
t.showMessage @ toastr.js?v=201806070714:1
(anonymous) @ toastr.js?v=201806070714:1
e.showMessages @ toastr.js?v=201806070714:1
(anonymous) @ toastr.js?v=201806070714:1
(anonymous) @ toastr.js?v=201806070714:1
(anonymous) @ toastr.js?v=201806070714:1
i @ toastr.js?v=201806070714:1
Promise.then (async)
u @ toastr.js?v=201806070714:1
(anonymous) @ toastr.js?v=201806070714:1
o @ toastr.js?v=201806070714:1
e.domContentLoadedHandler @ toastr.js?v=201806070714:1

Let me know if I am doing something wrong or you need more information.

**Comment by nabinked** [comment]
any update on this ?
