### ISSUE TITLE
XML Parsing Error: no root element found

### ISSUE THREAD

**Issue by amir3164** [nabinked/NToastNotify#56]
iam use messge with out quotes .but dont show alert message
when inspect browser this error:XML Parsing Error: no root element found
iam returm msg from sp database.

  var Result = _IUserService.UpdatePic(_UplaodImage);
      if (Result.Out_Procedure_Result_Status == 0)
        _toastNotification.AddErrorToastMessage(Result.Out_Procedure_Result_Status_Message.ToString())

**Comment by nabinked** [comment]
This does not sound like an error due cause by this lib. Reopen if you want to investigate more
