### ISSUE TITLE
Toastr not loading css from cdn

### ISSUE THREAD

**Issue by StrongGesmbH** [nabinked/NToastNotify#58]
After updating to latest version, toastr is only loading js file from CDN, and not css file

**Comment by nabinked** [comment]
Can you provide more details. I cant reproduce

**Comment by StrongGesmbH** [comment]
I had an issue where the styling dissapeared so i took a look at the network traffic and saw that no css file was loaded from the cdn.
But i resolved my issue with creating my own style sheet.
