### ISSUE TITLE
How Can I Change Toast Error Message Title ?

### ISSUE THREAD

**Issue by Timosis** [nabinked/NToastNotify#60]
NToastNotify is amazing and very useful. Thanks all of contrubiters. 
I want to change error message title to my own language. How can it be done ?

**Comment by nabinked** [comment]
You can set default title during startup service registration.

**Comment by nabinked** [comment]
Assuming this is solved. Closing it. Reopen if not

**Comment by Timosis** [comment]
Thanks. It works.
