### ISSUE TITLE
Positining toasts relative to a specific control

### ISSUE THREAD

**Issue by byteslash** [nabinked/NToastNotify#67]
im having issues to position toasts on  apage. The options presented by ToastPositions are insufficient for me as they seem to be relative to the entire page and not a specific form element.
I tried using ToastrOptions.Target but that doesnt work either. what does that property do?

im trying this on the latest ntoastnotify build with a .net core 2.2  mvc app.

**Comment by nabinked** [comment]
Please refer to the docs of `toastr` or `noty` and see if they meet your requirement. This is simply a wrapper around those libraries.

**Comment by nabinked** [comment]
Closing this as this is beyond the scope of this package.
