### ISSUE TITLE
No Toast from PartialView

### ISSUE THREAD

**Issue by manpreet311-hydra** [nabinked/NToastNotify#76]
Here's the case

I am loading a PartialView using an ajax "link". However, I have followed your tutorial and the same partialview works with fetch.

WHEN IS THERE AN AJAX CALL there is no toast notification.

I am assuming that 

`@await Component.InvokeAsync("NToastNotify")`

in the _Layout is not getting invoked. Not withstanding, I added that method in partial view still no result.

Please help.

**Comment by nabinked** [comment]
Show me more code please. Sorry, cannot understand whats going on.

**Comment by manpreet311-hydra** [comment]
Thanks for your reply,

If in short the problem can be described as "DISPLAYING TOAST FROM An AJAX CALL"

However I got it working, by handling my AJAX in jQuery

``
// Code removed for brevity

.ajaxSuccess(function (event, jqXHR, ajaxSettings, data) {
                //  Get response headers
                var toastMessages = jqXHR.getResponseHeader('X-NToastNotify-Messages');
                var reqWith = jqXHR.getResponseHeader('X-Requested-With');
                var partialViewResultHeader = jqXHR.getResponseHeader('X-Mars-Partial-View-Result');

                //  If there are toasts: 'X-NToastNotify-Messages' header
                if (decodeURI(toastMessages) !== decodeURIComponent(toastMessages)) {
                    var toastArray = jQuery.parseJSON(decodeURIComponent(toastMessages));
                    showToastArray(toastArray);
                }
            })
``
I hope it may help someone
