### ISSUE TITLE
Load toast js from local file

### ISSUE THREAD

**Issue by jfcaldeira** [nabinked/NToastNotify#78]
I have to use a web application on an intranet without access to cdn and I keep getting errors on console because it can't reach cdn.

Is there a way to change the plugin so it gets the javascript from a local file and not cdn?

**Comment by jfcaldeira** [comment]
closed this, apparently i only needed to download the files and have them on the wwwroot/lib/toastrjs folder and it uses them automatically when can't access cdn

**Comment by UweKeim** [comment]
I do think https://github.com/nabinked/NToastNotify/issues/138#issuecomment-739377896 is a more accurate and reliable answer (your suggestion did not work for me).
