### ISSUE TITLE
asp.net core 3.0 issue

### ISSUE THREAD

**Issue by dotnetshadow** [nabinked/NToastNotify#79]
Hi there,

I noticed when upgrading to .net core 3.0 preview 7 that the fileproviders registration has changed
https://github.com/aspnet/Extensions/issues/1325

**Comment by dotnetshadow** [comment]
I managed to get a version working under .net core 3.0 preview7, but after the first page load it would throw the following error:

```
NullReferenceException: Object reference not set to an instance of an object.

    Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
    Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionaryFactory.GetTempData(HttpContext context)
    NToastNotify.TempDataWrapper.get_TempData()
    NToastNotify.TempDataWrapper.Peek<T>(string key)
    NToastNotify.MessageContainers.TempDataMessageContainer<TMessage>.GetAll()
    NToastNotify.MessageContainers.TempDataMessageContainer<TMessage>.ReadAll()
    NToastNotify.ToastNotification<TMessage, TOptions>.ReadAllMessages()
    NToastNotify.NToastNotifyViewComponent.Invoke()
```

**Comment by dotnetshadow** [comment]
[NToastNotify-master.zip](https://github.com/nabinked/NToastNotify/files/3438946/NToastNotify-master.zip)

Sample with asp.net core 3.0 (WebApplicatio1)
It runs but after the first time it causes an error, if anyone can take a look

**Comment by nabinked** [comment]
Interesting. Could you have your changes in a seperate branch instead of the zip file? We can look at it when the 3.0 is officially released.

**Comment by dotnetshadow** [comment]
Yep I'll try and make a separate branch (I've never done this before)

Btw net core 3.0 preview 7 has a go live license, so it would be nice to get this library working since the changes made now wouldn't need to change by the time 3.0 is released

**Comment by dotnetshadow** [comment]
Created a branch for .net core 3.0 which you can check out
https://github.com/dotnetshadow/NToastNotify/tree/netcore3.0

Run WebApplication1, use `dotnet watch run` 
The first time the index page is loaded you will see the toastr, if you F5 (refresh) an exception occurs

**Comment by davidfowl** [comment]
There's a bug in the library, I submitted a PR to fix it see https://github.com/nabinked/NToastNotify/pull/80

**Comment by dotnetshadow** [comment]
Thank you so much David much appreciated

**Comment by dotnetshadow** [comment]
I think you still need the.net core 3.0 changes i might create a PR so you can merge the changes required to get it to work under.net core 3

**Comment by nabinked** [comment]
#80 would actually fix this error.

**Comment by dotnetshadow** [comment]
Ahh ok, I'll give it a go now that you have pushed it to nuget.
Originally the library wouldn't work under .net core 3.0 regardless of the bug because of the following:

`I noticed when upgrading to .net core 3.0 preview 7 that the fileproviders registration has changed
aspnet/Extensions#1325`

But I'll give it a try again from your nuget package and see if it indeed works without any other changes

**Comment by nabinked** [comment]
The file providers one could be different though. Let me know what issues you get this time.

**Comment by dotnetshadow** [comment]
I'm not home at the moment to try but basically I noticed in your app you used:

```
 services.Configure<RazorViewEngineOptions>(opts =>  
         opts.FileProviders.Add( new myFileProvider() ) 
     ); 
```

But in .net core 3.0 this has changed to
In ASP.NET Core 3.0, it is done using MvcRazorRuntimeCompilationOptions (needs to reference Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation:
```
     services.Configure<MvcRazorRuntimeCompilationOptions>(opts =>  
         opts.FileProviders.Add( new myFileProvider() ) 
     ); 
```

**Comment by dotnetshadow** [comment]
Just tried the latest nuget package and as suspected it doesn't work with asp.net core 3.0 due to the following error:
![image](https://user-images.githubusercontent.com/296247/62263962-54db5b00-b461-11e9-8708-33b5e18f495a.png)


I managed to get this working by modifying package references and `#if NETCORE_3.0` statements if interested

**Comment by dotnetshadow** [comment]
Added a PR for .net core 3.0 preview7

**Comment by AhmedHemdan21** [comment]
i'm using .net core 3.0 preview7 with version 5.0.12 and i'm facing same issue
