### ISSUE TITLE
Ajax request

### ISSUE THREAD

**Issue by jobairkhan** [nabinked/NToastNotify#8]
How could i show the message if the partial view is loaded by **ajax** post ?
A _bootsrap modal window_ is loaded via ajax request and i want to show a error message after the successful response. Do i need to add the component  seperately on the partial view

**Comment by nabinked** [comment]
I would not advise you to use the component inside a partial to show notification. What you can do is use the toastr JavaScript API to show a toast notification on the ajax success/complete event. 
```
//On Ajax success event in client side javascript
function(data){
  // Your logic here

  //show toast notification
  toastr.error('I do not think that word means what you think it means.', 'Error Title!')
}
```

**Comment by jobairkhan** [comment]
Is there any way that i could find the latest added message

**Comment by nabinked** [comment]
Can you give me more details regarding the case when you want to find the latest added message?

**Comment by jobairkhan** [comment]
Check the comments in code below

```
//On Ajax success event in client side javascript
function(data){
  // Your logic here

  //show toast notification
 // 'I do not think that word means what you think it means.' message added on server side
  toastr.showLastError()
}
```

**Comment by nabinked** [comment]
There is no such API in the toastr.js library

**Comment by nabinked** [comment]
#23 supports this.
