### ISSUE TITLE
last version error

### ISSUE THREAD

**Issue by RezaAVS** [nabinked/NToastNotify#82]
when update to last version : 5.0.11

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS18003	Build:No inputs were found in config file 'C:/Users/XXX/.nuget/packages/ntoastnotify/5.0.11/contentFiles/any/netstandard2.0/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","wwwroot"]'.	WebApplication2	C:\Users\BAHARI\source\repos\WebApplication2\WebApplication2\tsc	1

**Comment by nabinked** [comment]
Sound like a Visual Studio 2019 error. Cannot replicate this using CLI. Needs more investigation

**Comment by FabriDamazio** [comment]
Same error after update to the last version when i use Visual Studio. The version 5.0.10 works fine.

Maybe something with the dependabot PRs?

**Comment by nabinked** [comment]
Seems like the last release was made using a 3.0 preview sdk which messed up the whole contentFiles stuff. That was my bad. I apologize. Release 5.0.12 should fix that. Pushed to nuget as well.

**Comment by RezaAVS** [comment]
Hi,

No Problem

Thanks for your accountability

**Comment by nabinked** [comment]
Please close this if you think its resolved in the latest release

**Comment by RezaAVS** [comment]
Thanks for the problem solved
