### ISSUE TITLE
OnHidden

### ISSUE THREAD

**Issue by RezaAVS** [nabinked/NToastNotify#90]
Hi,

How to use OnHidden in ToastrOptions?

**Comment by RezaAVS** [comment]
![image](https://user-images.githubusercontent.com/51018682/65388636-9c43e080-dd5a-11e9-8a7d-049f93c5dffa.png)

**Comment by rbsdotnet** [comment]
Please Help me?
How to use OnHidden Function?

**Comment by nabinked** [comment]
OnHidden expects a js function. You cannot pass js function from c#. Sorry this property (or any other function property) needs to be removed.

**Comment by rbsdotnet** [comment]
I wanted to call a function after the notification was displayed

**Comment by rbsdotnet** [comment]
@nabinked 

Isn't there a way to use the OnHidden function?

**Comment by nabinked** [comment]
Currently there is no way that I can think of.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Reza Bahari <notifications@github.com>
पठाइयो: Sunday, September 29, 2019 5:11:38 AM
प्रापक: nabinked/NToastNotify <NToastNotify@noreply.github.com>
बोधार्थ: Nabin Karki Thapa <nabin@outlook.com>; Mention <mention@noreply.github.com>
विषय: Re: [nabinked/NToastNotify] OnHidden (#90)


@nabinked<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked&data=02%7C01%7C%7Cef268f61b16a4acae88908d74447b0ef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637052947012353539&sdata=CDzAEMJCNnF2SfoG5DeiFa8hfMNQrkuiAaEFjKErZ58%3D&reserved=0>

Isn't there a way to use the OnHidden function?
