### ISSUE TITLE
Demo sites non functional

### ISSUE THREAD

**Issue by bgiromini** [nabinked/NToastNotify#95]
Both demo sites are non functional. http://noty.azurewebsites.net/ seems to have reverted to the initial setup and http://toastr.azurewebsites.net/ is an error page

**Comment by nabinked** [comment]
I think currently azure Linux app service does not support aspnetcore 3.0 yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Brandon G <notifications@github.com>
पठाइयो: Sunday, September 29, 2019 4:56:33 AM
प्रापक: nabinked/NToastNotify <NToastNotify@noreply.github.com>
बोधार्थ: Subscribed <subscribed@noreply.github.com>
विषय: [nabinked/NToastNotify] Demo sites non functional (#95)


Both demo sites are non functional. http://noty.azurewebsites.net/<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fnoty.azurewebsites.net%2F&data=02%7C01%7C%7Cd5a87eb95aa14ef8f2db08d744459570%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637052937963469651&sdata=SBCImFjVbBVEVDFZuTcXOhDN2X%2FhmjrJ91aJqCJ1LxE%3D&reserved=0> seems to have reverted the the base code and http://toastr.azurewebsites.net/<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftoastr.azurewebsites.net%2F&data=02%7C01%7C%7Cd5a87eb95aa14ef8f2db08d744459570%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637052937963479656&sdata=Q8K7LallzjELhXOoSP7N2%2B8Yiz6GgjvzSDQ8gQD6Kuk%3D&reserved=0> is an error page

**Comment by nabinked** [comment]
fixed by #99
