### ISSUE TITLE
404 when deployed

### ISSUE THREAD

**Issue by axufuris** [nabinked/NToastNotify#98]
I have struggled with this for over a day now.  Can someone help me out.  I have a fairly simple Razor .net Core 3 app that I am trying to add NToastNotify to.  Everything works locally but when I publish to my server, it is telling me it can't find the file "_content/NToastNotify/toastr.js?something"  That content file is being created under my WWWRoot, but when it is creating the URL for my application, it is not putting in the application name. An example is https://myserverurl.com/RequestApplication/_content/NToastNotify/toastr.js?something but instead, it is creating it as https://myserverurl.com/_content/NToastNotify/toastr.js?something

Nothing special in my startup:

`if (environment == "Production")
            {
                //app.UseStatusCodePagesWithReExecute("/Application/Error", "?statusCode={0}");
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }
            else
            {
                app.UseDeveloperExceptionPage();
                //app.UseStatusCodePagesWithReExecute("/Application/Error", "?statusCode={0}");
                //app.UseExceptionHandler("/Error");
                //app.UseHsts();
            }

            app.UseSession();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseNToastNotify();
            app.UseCookiePolicy();
            app.UseAuthorization();
            app.UseAuthentication();

            app.UseRouting();

            //app.UseSaml();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });`

Here is my Configure Services:

`services.AddRazorPages().AddNToastNotifyToastr(new NToastNotify.ToastrOptions()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.BottomRight
            });`

**Comment by jakubsvobodacz** [comment]
The problem is that the js and css files that the NToastNotify is trying to get is a nonexisting cdn.

https://cdnjs.cloudflare.com/ajax/usva/libs/toastr.js/latest/toastr.min.css

I hoped that an update of the nuget will help but when I update from 5.0.8. to 6.0.1 then my project cannot find the libraries anymore.

**Comment by jakubsvobodacz** [comment]
Also why does all the updates since 5.0.8. have dependencies for aspnetcore 2.2 like Antiforgery etc.? There is no backward compatibility?

`Version conflict detected for Microsoft.AspNetCore.Antiforgery. Install/reference Microsoft.AspNetCore.Antiforgery 2.2.0 directly to project NN.NetworkManagementPortal to resolve this issue.  NN.NetworkManagementPortal -> NToastNotify 5.0.9 -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.2.0 -> Microsoft.AspNetCore.Antiforgery (>= 2.2.0)  NN.NetworkManagementPortal -> Microsoft.AspNetCore.App 2.1.1 -> `

Once I update to 6.0.1 the nuget is installed but I cannor reference the NToastNotify libraries:

`could not be found are you missing a using directive or an assembly reference`

`IMVC builder does not contain a definition for AddNToastNotifyToastr` etc.

**Comment by nabinked** [comment]
See the samples. They work fine when deployed. They both use 6.0.1

**Comment by jakubsvobodacz** [comment]
As I posted before:

Once I update to 6.0.1 the nuget is installed but I cannor reference the NToastNotify libraries:

could not be found are you missing a using directive or an assembly reference

IMVC builder does not contain a definition for AddNToastNotifyToastr etc.

using NToastNotify.Libraries; -- is not found -- it is greyed out

The samples cannot work if I cannot reference this: `using NToastNotify.Libraries`

**Comment by jakubsvobodacz** [comment]
Is there any way to fix the CDN links for production environments? It works on my localhost but since the cdns are not existing anymore it fails in prod.

**Comment by nabinked** [comment]
I am not sure what cdn issue you are talking about. The cdn links seems to be working fine.
![image](https://user-images.githubusercontent.com/7703179/67054163-56c6d780-f18f-11e9-8d03-6204fc8625ee.png)

**Comment by axufuris** [comment]
I'm not sure if it is the CDN or what.  All I know is, I followed the instructions in a straight up Razor template for .net core 3 and when my site is published to a virtual directory on IIS, it cannot access the correct files that are being created.

**Comment by jakubsvobodacz** [comment]
The 5.0.8. does have invalid link to a CDN containing the Ntoastify js and css. Can you please fix the link?

**Comment by axufuris** [comment]
@jakubsvobodacz If you have an issue with a different version of Ntoastify, please create your own ticket instead of high jacking mine!  I am currently on the most recent version and no one is even trying to help me resolve the issue or figure out what the problem is.

**Comment by axufuris** [comment]
@nabinked If everything was working fine, I wouldn't have created this ticket.  Telling me to see the examples is not helpful at all.  I literally explained in this ticket that I created a fresh new project from scratch and followed your example.  As soon as I publish up to a virtual directory it gives me errors that it can not find the files. Obviously this version has a bug, or your example is not complete.

**Comment by nabinked** [comment]
Did you try this in your startup
```
.AddNToastNotifyToastr(null, new NToastNotify.NToastNotifyOption()
    {
        ScriptSrc = "https://pagecdn.io/lib/toastr/2.1.4/toastr.min.js",
        StyleHref = "https://pagecdn.io/lib/toastr/2.1.4/toastr.min.css
    });
```

This allows you to provide cusom location for you js and css files.

**Comment by nabinked** [comment]
Closing this due to lack of response.
